### ISSUE TITLE
[Config Support]: Shared Cooldown for all Blueprint automations created

### ISSUE THREAD

**Issue by RyanPieters** [SgtBatten/HA_blueprints#348]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello,

I seem to be having trouble getting two notifications popping off at once. I did some trial and error and it very much seems that the "cooldown" within the UI is shared across all automations that I create.

I had a look in source and it looked like a name could be assigned for each cooldown. I tried that, but alas, I got the same result.

Testing:
I have two cameras and have set up an automation for each of them, notifying a device on a 30 second cooldown.

Running like a lunatic between the cameras, I immediately get the notification for the first, but it seems the second one only arrives 30 seconds later, even though they are two separate cameras on two separate automations.

I hope the above makes sense, and I appreciate any assistance on the matter.

### Version

0.12.0.6

### Automation config

```yaml
##Front Yard One
description: ""
alias: Frigate Notifications (0.12.0.6)
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.front_yard_1
    notify_device: xxx19f46e5d6xxxba8fxxxd41ebfxxxx ##Hidden some chars
    cooldown: 30

##FY2 is duplicated, with only camera being updated.
```

### Frigate Config

```yaml

```

**Comment by SgtBatten** [comment]
This is resolved in the upcoming beta. I'll try to port it over to stable for you

**Comment by RyanPieters** [comment]
Much appreciated @SgtBatten 🙏. Will await feedback.

**Comment by RyanPieters** [comment]
@SgtBatten, just want to make sure that by upcoming Beta, did you mean a version later than 0.12.0.6a? I've tried this version on the two cameras today and I'm still having the same issue.

However, I did notice that the two automations are triggering simultaneously, even if I'm only detected on the one camera (FY1), which makes no sense to me.

![Image](https://github.com/user-attachments/assets/a785a60e-bf36-4581-8fcc-3ea545b40724)

Adding my YAML above for the two as well.

Thanks very much and if there's anything I can do to assist, please let me know 👍

```yaml

## Front Yard 1 Camera
alias: Frigate Notifications (0.12.0.6a) - FY1 Test
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.front_yard_1
    notify_device: Devicexxxxxx
    base_url: HA URL
    cooldown: 30

## Front Yard 2 Camera
alias: Frigate Notifications (0.12.0.6a) - FY2 Test
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.front_yard_2
    notify_device: Devicexxxxxx
    base_url: HA URL
    cooldown: 30

**Comment by SgtBatten** [comment]
All the mqtt messages go to the same topic so that's why it triggers twice. I was under the impression conditions would stop the trigger from registering but I guess not which is unfortunate. 

If you really must stick with the events topic and use a cooldown then you will need to roll back or edit the blueprint to be single camera logic again where is checks the mqtt message for the camera name during the trigger process. Unfortunately HA doesn't allow the necessary template to filter based on the camera within the trigger now that we have the multi camera setup.

**Comment by RyanPieters** [comment]
Thanks for the info @SgtBatten, I'll have a look and see what I can do with regards to the events topic, if all else fails I'll perform the rollback of the blueprint.

**Comment by RyanPieters** [comment]
Thanks for the advice, changing/splitting the frigate/events topic to be camera specific allowed me to assign a custom MQTT topic for each Automation.

I have used the Node-RED addon in HA to split the topics:

![Image](https://github.com/user-attachments/assets/57e1165e-4d72-4001-ba97-4f50f3126bec)

I'm hoping the above helps others new to HA/Frigate as well 😊.

Thanks again @SgtBatten.

**Comment by SgtBatten** [comment]
Impressive. Thanks for sharing, This is great info.
